import { Button, HTag } from '@/components';
import Head from 'next/head';


export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HTag tag="h1">Текст</HTag>
			<Button arrow='down' appearance='primary'>Кнопка</Button>
			<Button appearance='ghost'>Кнопка</Button>
		</>);
}
